config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :collections do
    member do
      post :public
      post :hide
    end
  end

  resources :items, except: [:index]
  resources :offers do
    member do
      post :accept
      post :reject
    end
  end

  resources :comments, only: [:create]
  resources :profiles, only: [:show]

  get 'home/index'

  devise_for :users
  root 'home#index'
end

app/models/collection.rb
class Collection < ActiveRecord::Base

  # relations
	has_many :items, dependent: :destroy
	belongs_to :user

  # validations
  validates :name, :user_id, presence: true
  validates :name, length: { maximum: 50 }

  #scopes
  scope :not_hide, -> { where(public: true) }
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy, :public, :hide]

  # GET /collections
  # GET /collections.json
  def index
    if params[:user_id]
      user = User.find(params[:user_id])
      if user == current_user
        @collections = user.collections.order(updated_at: :asc)
      else
        @collections = user.collections.not_hide.order(updated_at: :asc)
      end
    else
      @collections = Collection.all.not_hide.order(updated_at: :asc)
    end
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
    authorize @collection
    @items = @collection.items
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
    authorize @collection
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(collection_params)
    @collection.user_id = current_user.id
    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    authorize @collection
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    authorize @collection
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def public
    authorize @collection
    @collection.update(public: true) unless @collection.public
    redirect_to :back, notice: "Colelction: #{@collection.name} is now public for other users"
  end

  def hide
    authorize @collection
    @collection.update(public: false) if @collection.public
    redirect_to :back, notice: "Collection: #{@collection.name} is now hidden form other users"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.require(:collection).permit(:name, :description, :contains, :tags, :image)
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_form.html.haml
= simple_form_for @collection, html: { class: "form-horizontal", role: "form" } do |f|
  -if @collection.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@collection.errors.count, "error")} prohibited this collection from being saved:"

      %ul
        - @collection.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    .row
      .col-sm-offset-2.col-sm-10
        = f.label :name, class: 'control-label'
        = f.text_field :name, class: 'form-control'
      .col-sm-offset-2.col-sm-10
        = f.label :tags, class: 'control-label'
        = f.text_field :tags, class: 'form-control'
      .col-sm-offset-2.col-sm-10
        = f.label :contrains, class: 'control-label'
        = f.text_area :contains, class: 'form-control'
    .row
      .col-sm-offset-2.col-sm-10
        = f.submit class: 'btn btn-primary'

app/views/collections/edit.html.haml
.panel.panel-default
  .panel-heading
    .row
      .col-md-8
        %h2 Edit collection
      .col-md-4
        .pull-right
          = link_to @collection, class: 'btn btn-primary' do
            %span.glyphicon.glyphicon-info-sign
            Show
  .panel-body
    .row
      .col-md-8.col-md-offset-2
        = render 'form'

app/views/collections/index.html.haml
.panel.panel-default
  .panel-heading
    .row
      .col-md-8
        %h2 Collection list
      .col-md-4
        .pull-right
          = link_to new_collection_path, class: 'btn btn-primary' do
            %span.glyphicon.glyphicon-plus
            New collection
  .panel-body
    .table-responsive
      %table.table.table-striped.table-bordered{id: "data_table"}
        %thead
          %tr
            %th Name
            %th Contains
            %th Tags
            %th
        %tbody
          - @collections.each do |collection|
            %tr
              %td= link_to collection.name, collection
              %td= collection.contains
              %td= collection.tags
              %td
                -if policy(collection).update?
                  - if collection.public
                    = link_to 'Hide', hide_collection_path(collection), method: :post
                  - else
                    = link_to 'Public', public_collection_path(collection), method: :post
                  = link_to 'Edit', edit_collection_path(collection)
                  = link_to 'Destroy', collection, data: { confirm: 'Are you sure?' }, method: :delete
:javascript
  $(document).ready(function(){
    $("#data_table").DataTable({
      "order": [[ 0, "desc" ]]
    });
  });

app/views/collections/new.html.haml
.panel.panel-default
  .panel-heading
    .row
      .col-md-8
        %h2 New collection
  .panel-body
    .row
      .col-md-8.col-md-offset-2
        = render 'form'

app/views/collections/show.html.haml
.panel.panel-default
  .panel-heading
    .row
      .col-md-8
        %h2
          Collection:
          =@collection.name
      .col-md-4
        .pull-right
          - if current_user.collections.include?(@collection)
            - if @collection.public
              = link_to 'Hide', hide_collection_path(@collection), method: :post, class: 'btn btn-primary'
            - else
              = link_to 'Public', public_collection_path(@collection), method: :post, class: 'btn btn-primary'
            = link_to edit_collection_path(@collection), class: 'btn btn-primary' do
              %span.glyphicon.glyphicon-pencil
              Edit
            = link_to new_item_path(collection_id: @collection.id), class: 'btn btn-primary' do
              %span.glyphicon.glyphicon-plus
              Add items
  .panel-body
    .row
      .col-md-5.text-center
        %h3 Contrains:
        = @collection.contains
      .col-md-5.text-center
        %h3 Tags:
        = @collection.tags
    .row.col-md-10.col-md-offset-1
      .row
        .col-md-8
          %h2 Items:
      .row
        %table.table.table-striped.table-bordered{id: 'data_table'}
          %thead
            %tr
              %th Name
              %th Description
              %th Year
              %th Actions

          %tbody
            - @items.each do |item|
              %tr
                %td= item.name
                %td= item.description
                %td= item.year
                %td
                  = link_to 'Show', item
                  - if policy(item).update?
                    = link_to 'Edit', edit_item_path(@collection)
                    = link_to 'Destroy', item, data: { confirm: 'Are you sure?' }, method: :delete

:javascript
  $(document).ready(function(){
    $("#data_table").DataTable({
      "order": [[ 0, "desc" ]]
    });
  });