config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :collections do
    member do
      post :public
      post :hide
    end
  end

  resources :items, except: [:index]
  resources :offers do
    member do
      post :accept
      post :reject
    end
  end

  resources :comments, only: [:create]
  resources :profiles, only: [:show]

  get 'home/index'

  devise_for :users
  root 'home#index'
end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :seller, foreign_key: :seller_id, class_name: User
  belongs_to :buyer, foreign_key: :buyer_id, class_name: User
  belongs_to :item
  acts_as_commentable

  enum status: [:unread, :read, :accepted, :rejected]

  validates :seller, :buyer, :item, presence: true

  scope :unread, -> { where(status: 'unread') }

  def finished?
    status == 'accepted' || status == 'rejected'
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController

  def index
    @to_buy = current_user.buy_offers
    @to_sell = current_user.sell_offers
  end

  def show
    @offer = Offer.find(params[:id])
    authorize @offer
    @offer.update(status: 'read') if @offer.seller == current_user && @offer.status == 'unread'
    @comments = @offer.comments
    @comment = Comment.new
  end

  def accept
    @offer = Offer.find(params[:id])
    authorize @offer
    @offer.update(status: 'accepted')
    redirect_to offers_path, notice: 'Accepted'
  end

  def reject
    @offer = Offer.find(params[:id])
    authorize @offer
    @offer.update(status: 'rejected')
    redirect_to offers_path, notice: 'Rejected'
  end

  def create
    offer = Offer.new(offer_params)
    offer.seller = Item.find(offer.item_id).user
    offer.buyer = current_user
    if offer.save
      redirect_to collection_path(offer.item.collection_id), notice: 'Offer created.'
    else
      redirect_to item_path(offer.item), notice: 'Error, try again later.'
    end
  end

  protected

  def offer_params
    params.require(:offer).permit(:item_id, :description)
  end

end

app/views/offers/index.html.haml
.panel.panel-default
  .panel-heading
    .row
      .col-md-12
        %h2 Offers
  .panel-body
    .row
      .col-md-12
        %h3 Offers you have made
        .table-responsive
          %table.table.table-striped.table-bordered{id: 'data_table'}
            %thead
              %tr
                %th Seller
                %th Item name
                %th Description
                %th Status
                %th
            %tbody
              - @to_buy.each do |offer|
                %tr
                  %td= link_to offer.seller.nickname, profile_path(offer.seller)
                  %td= offer.item.name
                  %td= offer.description
                  %td= offer.status
                  %td= link_to 'Show', offer
    .row
      .col-md-12
        %h3 Offers for you
        .table-responsive
          %table.table.table-striped.table-bordered{id: 'data_table_two'}
            %thead
              %tr
                %th Requester
                %th Item name
                %th Description
                %th
            %tbody
              - @to_sell.each do |offer|
                %tr
                  %td= link_to offer.buyer.nickname, profile_path(offer.buyer)
                  %td= offer.item.name
                  %td= offer.description
                  %td
                    - if offer.finished?
                      = offer.status
                    - else
                      = link_to 'Show', offer
                      = link_to 'Accept', accept_offer_path(offer.id), method: :post
                      = link_to 'Reject', reject_offer_path(offer.id), method: :post
:javascript
  $(document).ready(function(){
    $("#data_table").DataTable({
      "order": [[ 0, "desc" ]]
    });
  });
  $(document).ready(function(){
    $("#data_table_two").DataTable({
      "order": [[ 0, "desc" ]]
    });
  });

app/views/offers/show.html.haml
.panel.panel-default
  .panel-heading
    .row
      .col-md-12
        %h2= "Item: #{@offer.item.name}"
  .panel-body
    .row
      .col-md-12
        %h3= "Description: #{@offer.description}"
        %p= "Buyer: #{@offer.seller.nickname}"
        %p= "Seller: #{@offer.seller.nickname}"
        - if @offer.seller == current_user
          - if @offer.finished?
            = @offer.status
          - else
            = link_to 'Accept', accept_offer_path(@offer.id), method: :post
            = link_to 'Reject', reject_offer_path(@offer.id), method: :pos

        %h3 #{ Comment.model_name.human }:
        .box-comment
          - if @comments.any?
            - @comments.by_created_time.each do |comment|
              = render comment
        = form_for @comment, url: comments_path, method: :post do |f|
          .row
            .col-xs-8.col-sm-8.col-lg-8
              .form-group
                = f.text_area :comment, placeholder: 'comment', size: '8x2', class: 'form-control comment-comment'
                = f.hidden_field :commentable_id, value: @offer.id
                = f.hidden_field :commentable_type, value: @offer.class.name
            .col-xs-4.col-sm-4.col-lg-4
              = f.submit 'Add', class: 'btn btn-primary btn-lg add-comment-button'