config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :collections do
    member do
      post :public
      post :hide
    end
  end

  resources :items, except: [:index]
  resources :offers do
    member do
      post :accept
      post :reject
    end
  end

  resources :comments, only: [:create]
  resources :profiles, only: [:show]

  get 'home/index'

  devise_for :users
  root 'home#index'
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.haml
- if current_user
  %li= link_to 'All Collections', collections_path
  %li= link_to 'My Collections', collections_path(user_id: current_user)
  %li= link_to "Mailbox (#{@unread})", offers_path
  %li= link_to 'Edit profile', edit_user_registration_path
  - if current_user.admin?
    %li= link_to 'Admin', rails_admin_path
  %li= link_to 'Sign out', destroy_user_session_path, :method=>'delete'
- else
  %li= link_to 'Sign in ', new_user_session_path
  %li= link_to 'Sign up', new_user_registration_path

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
= render 'layouts/nav_links_for_auth'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Collectionus'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Collectionus'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body.layout-boxed
    %header
      = render 'layouts/navigation'
    #main-container.container
      .row
        #content.col-md-12
          %main{role: 'main'}
            = render 'layouts/messages'
            = yield